#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

source "$CONFIG_DIR/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=37 blur_radius=0 color=0x00ffffff

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
    padding_left=5
    padding_right=5
    icon.font="Hack Nerd Font Mono:Bold:17.0"
    label.font="JetBrains Mono:Bold:14.0"
    icon.color=$WHITE
    label.color=$WHITE
    background.drawing=off
    background.color=$ITEM_BG_COLOR
    background.border_color=0xffffffff
    background.height=24
    background.corner_radius=5
    icon.padding_left=8
    icon.padding_right=8
    label.padding_left=8
    label.padding_right=8
)
sketchybar --default "${default[@]}"

# Right Side Items
# Calendar
sketchybar --add item date right \
    --set date \
    update_freq=3600 \
    script="$PLUGIN_DIR/date.sh" \
    icon.drawing=off \
    label.font="JetBrains Mono:Regular:9" \
    label.padding_left=6 \
    width=0 \
    label.align=center \
    background.drawing=off \
    y_offset=6

sketchybar --add item time right \
    --set time \
    update_freq=30 \
    script="$PLUGIN_DIR/time.sh" \
    icon.drawing=off \
    label.font="JetBrains Mono:Bold:13" \
    label.padding_left=6 \
    width=0 \
    label.align=center \
    background.drawing=off \
    y_offset=-4
# Spacer
sketchybar --add item spacer_right right \
    --set spacer_right \
    width=91 \
    background.drawing=off \
    label.drawing=off \
    icon.drawing=off
# Battery
sketchybar --add item battery right \
    --set battery \
    script="$PLUGIN_DIR/battery.sh" \
    background.drawing=off \
    icon.padding_right=4 \
    update_freq=60

# cpu_usage
sketchybar --add item cpu_usage right \
    --set cpu_usage \
    script="$PLUGIN_DIR/cpu_usage.sh" \
    background.drawing=off \
    update_freq=5 \
    icon.padding_right=4 \
    icon="" \
    background.corner_radius=12 \
    icon.font="Hack Nerd Font Mono:Bold:20.0"
# SSD_usage
sketchybar --add item ssd_usage right \
    --set ssd_usage \
    script="$PLUGIN_DIR/ssd_usage.sh" \
    background.drawing=off \
    update_freq=60 \
    icon="" \
    icon.padding_right=4 \
    icon.font="Hack Nerd Font Mono:Bold:20.0"

#Bracket for calendar, battery
sketchybar --add bracket right_side date time \
    --set right_side background.color=0x5e000000 \
    background.drawing=on \
    background.height=28 \
    background.corner_radius=12
# Bracket for sys_info
sketchybar --add bracket sys_info cpu_usage ssd_usage battery \
    --set sys_info background.color=0x5e000000 \
    background.drawing=on \
    background.height=28 \
    background.corner_radius=12

# Left Side Items
sketchybar --add item apple left \
    --set apple \
    icon="" \
    icon.font="Hack Nerd Font Mono:Bold:25.0" \
    background.drawing=off \
    background.height=28 \
    background.corner_radius=12 \
    icon.padding_right=0 \
    icon.color=0xffcba6f7

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_monitor_change
sketchybar --add event aerospace_focus_changed

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        drawing=on \
        label.drawing=on \
        label.font="sketchybar-app-font:Regular:16.0" \
        background.drawing=on \
        background.color=0x00ffffff \
        icon="$sid" \
        icon.padding_left=10 \
        label.padding_right=15 \
        label.padding_left=0 \
        label.y_offset=-1 \
        click_script="aerospace workspace $sid" \
        script="$PLUGIN_DIR/aerospace.sh $sid"
done

for mid in $(aerospace list-monitors | cut -c1); do
    for sid in $(aerospace list-workspaces --monitor $mid --empty no); do
        apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

        sketchybar --set space.$sid drawing=on

        icon_strip=" "
        if [ "${apps}" != "" ]; then
            while read -r app; do
                icon_strip+=" $($PLUGIN_DIR/icon_map_fn.sh "$app")"
            done <<<"${apps}"
        else
            icon_strip=""
        fi
        sketchybar --set space.$sid label="$icon_strip"
    done
done

sketchybar --add item icon_refresher left \
    --set icon_refresher drawing=off \
    width=0 \
    script="$PLUGIN_DIR/icon_refresh.sh" \
    --subscribe icon_refresher aerospace_focus_changed aerospace_workspace_change

sketchybar --add item front_app left \
    --set front_app icon.drawing=off \
    label.font="Hack Nerd Font Mono:Bold:14" \
    script="$PLUGIN_DIR/front_app.sh" \
    background.drawing=on \
    background.color=0x5e000000 \
    background.height=28 \
    background.corner_radius=12 \
    --subscribe front_app front_app_switched

sketchybar --add bracket left_bracket apple space.6 \
    --set left_bracket background.color=0x5e000000 \
    background.drawing=on \
    background.height=28 \
    background.corner_radius=12
sketchybar --update
